looker: always initialize `log`
   2) Loki API test suite
       long dummystream insert, validate via query:
     TypeError: Cannot read property 'info' of undefined

Signed-off-by: Dr. Jan-Philip Gehrcke <jp@opstrace.com>

looker: log.ts: expect logger to be defined

Signed-off-by: Dr. Jan-Philip Gehrcke <jp@opstrace.com>