ci: preamble: do not disable contrlr pkg
The CLI build has some implicit surprising
dependency on the controller.

While building the CLI tsc complains that

[2021-08-16T19:12:22Z] ../controller/src/dbSDK.ts(17,31):
   error TS2307: Cannot find module 'graphql-request' or its
   corresponding type declarations.../controller/src/dbSDK.ts

The CLI build should not trigger a (partial) controller
build.

As per the dependencies, the CLI depends on controller-config
but not on .. well.

Signed-off-by: Dr. Jan-Philip Gehrcke <jp@opstrace.com>