cli: custom ucc validation for auth0 params
Tried this out manually:

   error: invalid config document: 'custom_auth0_client_id'
   requires 'custom_auth0_domain' and vice versa

Signed-off-by: Dr. Jan-Philip Gehrcke <jp@opstrace.com>